CREATE TABLE IF NOT EXISTS `volunteer_applications` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `first_name` VARCHAR(150) NOT NULL,
  `last_name` VARCHAR(150) NOT NULL,
  `whatsapp_number` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(50) NOT NULL,
  `age` TINYINT UNSIGNED NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `reason` TEXT NOT NULL,
  `has_volunteered_before` ENUM('yes', 'no') NOT NULL DEFAULT 'no',
  `experience` TEXT DEFAULT NULL,
  `confirm_correct` TINYINT(1) NOT NULL DEFAULT 0,
  `agree_rules` TINYINT(1) NOT NULL DEFAULT 0,
  `status` ENUM('new', 'contacted', 'approved', 'rejected') NOT NULL DEFAULT 'new',
  `source` ENUM('website', 'admin') NOT NULL DEFAULT 'website',
  `admin_notes` TEXT DEFAULT NULL,
  `submitted_by_user_id` INT UNSIGNED DEFAULT NULL,
  `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `fk_volunteer_applications_user` FOREIGN KEY (`submitted_by_user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  INDEX `idx_volunteer_applications_status` (`status`),
  INDEX `idx_volunteer_applications_source` (`source`),
  INDEX `idx_volunteer_applications_phone` (`phone_number`),
  INDEX `idx_volunteer_applications_deleted` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
